# Generated by Django 2.2 on 2022-02-28 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("color", models.CharField(default="", max_length=20)),
                ("method", models.IntegerField(default=0)),
                ("end", models.DateTimeField(blank=True, default=None)),
                ("isPermanent", models.BooleanField(default=False)),
                ("isOpen", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("discordID", models.CharField(max_length=50)),
                ("isActivated", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("sid", models.CharField(max_length=100)),
                ("pp", models.FloatField(default=0)),
                ("borderPP", models.FloatField(default=0)),
                ("message", models.CharField(blank=True, default="", max_length=50)),
                ("isAbstein", models.BooleanField(default=False)),
                ("isStaff", models.BooleanField(default=False)),
                ("twitter", models.CharField(blank=True, default="", max_length=50)),
                ("twitch", models.CharField(blank=True, default="", max_length=50)),
                ("booth", models.CharField(blank=True, default="", max_length=50)),
                ("imageURL", models.CharField(default="", max_length=100)),
                ("hmd", models.CharField(default="", max_length=50)),
                (
                    "rival",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.Player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("author", models.CharField(default="", max_length=100)),
                ("diff", models.CharField(default="", max_length=20)),
                ("char", models.CharField(default="", max_length=50)),
                ("notes", models.IntegerField(default=0)),
                ("bsr", models.CharField(default="", max_length=10)),
                ("hash", models.CharField(default="", max_length=100)),
                ("lid", models.CharField(default="", max_length=10)),
                ("color", models.CharField(default="white", max_length=20)),
                ("imageURL", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("acc", models.FloatField(default=0)),
                ("rawPP", models.FloatField(default=0)),
                ("miss", models.IntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.League"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.Player"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.Song"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("image", models.CharField(default="", max_length=200000)),
                ("description", models.CharField(default="", max_length=200)),
                ("isEditable", models.BooleanField(default=False)),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.Player",
                    ),
                ),
                (
                    "recommend",
                    models.ManyToManyField(
                        blank=True, related_name="recommend", to="app.Song"
                    ),
                ),
                ("songs", models.ManyToManyField(to="app.Song")),
            ],
        ),
        migrations.AddField(
            model_name="league",
            name="invite",
            field=models.ManyToManyField(
                blank=True, related_name="invite", to="app.Player"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="app.Player",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="player",
            field=models.ManyToManyField(blank=True, to="app.Player"),
        ),
        migrations.AddField(
            model_name="league",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Playlist",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="virtual",
            field=models.ManyToManyField(
                blank=True, related_name="virtual", to="app.Player"
            ),
        ),
    ]
