# Generated by Django 2.2 on 2022-03-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_auto_20220301_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="inDiscord",
            field=models.BooleanField(default=False),
        ),
    ]
