# Generated by Django 2.2 on 2022-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='league', to='app.Player'),
        ),
    ]
