# Generated by Django 2.2 on 2022-03-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_auto_20220316_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headline",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Player",
            ),
        ),
    ]
