# Generated by Django 2.2 on 2022-04-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_player_usercolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Song')),
            ],
        ),
    ]
