# Generated by Django 2.2 on 2022-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220409_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='isOfficial',
            field=models.BooleanField(default=False),
        ),
    ]
