# Generated by Django 2.2 on 2022-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_league_isofficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.CharField(default='', max_length=400000),
        ),
    ]
