# Generated by Django 2.2 on 2022-11-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_league_border_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='CoEditor',
            field=models.ManyToManyField(related_name='co_editor', to='app.Player'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='app.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='ownerComment',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
