# Generated by Django 2.2 on 2022-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20221115_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
