# Generated by Django 2.2 on 2022-11-19 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_score_decorate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeagueComment",
            new_name="Participant",
        ),
    ]
