# Generated by Django 2.2 on 2022-11-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20221120_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
