# Generated by Django 2.2 on 2022-11-19 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_score_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="league",
            old_name="method",
            new_name="max_valid",
        ),
    ]
