# Generated by Django 2.2 on 2022-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20221121_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='decorate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
