# Generated by Django 2.2 on 2023-01-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_score_beatleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='beatleader',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
