# Generated by Django 2.2 on 2023-01-21 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0037_player_yurufuwa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="Yurufuwa",
            new_name="yurufuwa",
        ),
    ]
