# Generated by Django 2.2 on 2023-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_jpmap_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpmap',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
