# Generated by Django 2.2 on 2023-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_player_mapper_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="accPP",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="passPP",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="techPP",
            field=models.FloatField(default=0),
        ),
    ]
