# Generated by Django 2.2 on 2023-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_dga'),
    ]

    operations = [
        migrations.AddField(
            model_name='dga',
            name='player_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
