# Generated by Django 3.2.18 on 2023-06-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0048_auto_20230427_2232"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="bid",
            field=models.CharField(default="", max_length=50),
        ),
    ]
