# Generated by Django 3.2.18 on 2023-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20230617_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
