# Generated by Django 3.2.18 on 2023-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_songinfo_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="prohibited_leagues",
            field=models.ManyToManyField(
                blank=True,
                related_name="_app_league_prohibited_leagues_+",
                to="app.League",
            ),
        ),
    ]
