# Generated by Django 3.2.18 on 2023-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_league_prohibited_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpmap',
            name='name',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
